--- #YAML:1.0
name:                WWW-Analytics-MultiTouch
version:             0.06
abstract:            Multi-touch web analytics, using Google Analytics
license:             perl
author:              
    - Jon Schutz <jon at jschutz.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config::General:               0
    Data::Dumper:                  0
    DateTime:                      0
    DateTime::Duration:            0
    Digest::MD5:                   0
    File::Temp:                    0
    Getopt::Long:                  0
    Hash::Merge:                   0
    IO::File:                      0
    List::Util:                    0
    LWP::UserAgent:                0
    Net::Google::Analytics:        0
    Net::Google::AuthSub:          0
    Params::Validate:              0
    Pod::Usage:                    0
    POSIX:                         0
    Spreadsheet::WriteExcel:       2.37
    Test::More:                    0
    Text::CSV_XS:                  0.73
    Text::Table:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
